/**
 * Constants Barrel Export
 *
 * Public API for application-wide constants.
 */

// UI Constants
export {
	MAX_CHORD_FONT_SIZE,
	MAX_ALTERNATIVES_FONT_SIZE,
	MAX_NOTE_FONT_SIZE,
	FONT_SIZE_MARGIN_RATIO,
	FONT_SIZE_TOLERANCE,
	FONT_SIZE_RESIZE_DEBOUNCE,
	ALTERNATIVES_MARGIN_TOP,
	COLOR_TRANSITION_DURATION,
	OPACITY_TRANSITION_DURATION,
	SETTINGS_FOCUS_DELAY
} from './ui';

// MIDI Constants
export { SEMITONES_PER_OCTAVE, MIDI_NUMBER, PIANO_88_KEY_RANGE, SUSTAIN_PEDAL } from './midi';

// Keyboard Constants
export {
	KEYBOARD_VIEWBOX_WIDTH,
	KEYBOARD_VIEWBOX_HEIGHT,
	WHITE_KEY_WIDTH,
	WHITE_KEY_HEIGHT,
	BLACK_KEY_WIDTH,
	BLACK_KEY_HEIGHT,
	KEY_CORNER_RADIUS_RATIO,
	LABEL_Y_OFFSET_RATIO,
	LABEL_FONT_SIZE_RATIO,
	MIN_MIDI_NUMBER,
	MAX_MIDI_NUMBER,
	WHITE_KEY_COUNT,
	BLACK_KEY_COUNT
} from './keyboard';
